### ISSUE TITLE
[FEAT] Send Queries

### ISSUE THREAD

**Issue by rpereira-tae** [taecontrol/larvis#18]
1. How to capture database query data.
2. Design data structure.
3. Solution implementation.

**Comment by rpereira-tae** [comment]
https://github.com/laravel/telescope/blob/4.x/src/Watchers/QueryWatcher.php

**Comment by rpereira-tae** [comment]
@AlexisTAE Cuál bloqueo tienes con este issue?

**Comment by AlexisTAE** [comment]
@rpereira-tae ahorita tratando de entender que hacen en telescope para ver los queries y no se si las estructuras las pondria en un Value objects
