### ISSUE TITLE
[FEAT] `QueryData` have to include a field `queriedAt` + Fix class field `connection_name` into `connectionName`.

### ISSUE THREAD

**Issue by rpereira-tae** [taecontrol/larvis#27]
The query data is required to include the timestamp of when the call occurred. For this a field called `queriedAt` will be added.

Also 

The class field name `connection_name` is required to be refactored into `connectionName`.

**Comment by AlexisTAE** [comment]
el connection_name ya esta asi

**Comment by AlexisTAE** [comment]
no es mejor queried_at porque asi esta en exceptions thrown_at asi se es consistente
